---
abstract: 'Report prerequisite modules and version numbers'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Install::RequiresList
name: Module-Install-RequiresList
no_index:
  directory:
    - inc
    - t
requires:
  CPAN::Meta::YAML: 0.003
  IO::All: 0.41
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
