---
abstract: 'Report prerequisite modules and version numbers'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-Install-RequiresList
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  CPAN::Meta::YAML: '0.003'
  IO::All: '0.41'
  JSON: '2.53'
  Module::Install: '1.10'
  Template::Toolkit::Simple: '0.13'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/module-install-requireslist-pm/issues
  homepage: https://github.com/ingydotnet/module-install-requireslist-pm
  repository: https://github.com/ingydotnet/module-install-requireslist-pm.git
version: '0.13'
